app/models.py
# -*- coding:utf-8 -*- 
# author: zchong

import json

from datetime import datetime
from sqlalchemy import DateTime


from . import db


class User(db.Model):
    __tablename__ = 'user'

    id = db.Column(db.Integer, primary_key=True)
    username = db.Column(db.String(64), unique=True, index=True)
    password = db.Column(db.String(128))
    alias = db.Column(db.String(128))
    email = db.Column(db.String(64), unique=True, index=True)
    createdt = db.Column(db.DateTime)
    updatedt = db.Column(db.DateTime)




# 博客信息
class Article(db.Model):
    __tablename__ = 'article'

    id = db.Column(db.INTEGER, primary_key=True)
    title = db.Column(db.String(128))
    classfication = db.Column(db.String(32))
    abstract = db.Column(db.String(4000))
    content = db.Column(db.Text)
    author = db.Column(db.String(32))
    createdt = db.Column(db.DateTime, default=datetime.utcnow)
    updatedt = db.Column(db.DateTime, default=datetime.utcnow)

    def __init__(self,title,classfication,abstract,content):
        self.title = title
        self.classfication = classfication
        self.abstract = abstract
        self.content = content
        self.author = 'zchong'
        # self.createdt = datetime.utcnow
        # self.updatedt = datetime.utcnow

# 分类
class Classify(db.Model):
    __tablename__ = 'classify'
    id = db.Column(db.CHAR(12), primary_key=True)
    name = db.Column(db.String(128))
    create_time = db.Column(db.DateTime, default=datetime.utcnow)
    update_time = db.Column(db.DateTime, default=datetime.utcnow)

    # 获取所有的分类
    @staticmethod
    def getClassifys():
        classifys = Classify.query.all()
        return classifys


# 博客-分类信息
class BlogClassify(db.Model):
    __tablename__ = 'blog_classify'

    id = db.Column(db.CHAR(12), primary_key=True)
    blog_id = db.Column(db.CHAR(12), db.ForeignKey('blog.id'))
    classify_id = db.Column(db.CHAR(12), db.ForeignKey('classify.id'))
    create_time = db.Column(db.DateTime, default=datetime.utcnow)
    update_time = db.Column(db.DateTime, default=datetime.utcnow)


def datetimestr(datetime):
    return datetime.strftime('%Y-%m-%d %H:%M:%S')


def to_json(inst, cls):
    convert = dict()
    convert[datetime] = datetimestr
    d = dict()
    for c in cls.__table__.columns:
        v = getattr(inst, c.name)
        if type(v) in convert.keys() and v is not None:
            try:
                d[c.name] = convert[type(v)](v)
            except:
                d[c.name] = "Error: Failed to covert using ", str(convert[c.type])
        elif v is None:
            d[c.name] = str()
        else:
            d[c.name] = v
    return json.dumps(d, ensure_ascii=False)

app/__init__.py
# -*- coding:utf-8 -*-
# author: zchong

from flask import Flask
from config import Config
#from flask_wtf.csrf import CSRFProtect
from flask_sqlalchemy import SQLAlchemy

db = SQLAlchemy()

def create_app():
    app = Flask(__name__)
    app.config.from_object(Config)
    Config.init_app(app)
    #CSRFProtect(app)

    # 初始化db
    db.init_app(app)

    # init public param
    app.config['UPLOAD_FOLDER'] = getUploadPath()

    from .admin import admin
    app.register_blueprint(admin, url_prefix='/admin')

    from .auth import auth
    app.register_blueprint(auth,url_prefix='/auth')

    from .main import main
    app.register_blueprint(main, url_prefix='')

    return app

def getUploadPath():
    import os
    runPath = os.path.split(os.path.realpath(__file__))[0]
    upload = os.path.join(runPath, "static", "upload")
    return upload

app/admin/__init__.py
from flask import Blueprint

admin = Blueprint('admin', __name__)

from . import views

app/admin/views.py
from flask import render_template, redirect, request, url_for, flash, jsonify, make_response
from flask_login import login_user, login_required, logout_user
import json
from functools import partial
from app.models import Article, BlogClassify
from app import db

from . import admin


@admin.route('/edit.html')
def index():
    return render_template('edit.html')
    # return classify('9D4ABD5A8B12')
    # o = User.query.all()
    # print(o.__dict__)
    # author='zchong'
    # json_str = jsonify(o)
    # return render_template("index.html",author=author)
    # return make_response(jsonify(o.__dict__))
    # print(o.alias)
    # json_dumps = partial(json.dumps, ensure_ascii=False, sort_keys=True)
    # return jsonify("张冲是我")
    # classifys = Classify.getClassifys()


@admin.route('/uploadText', methods=['POST'])
def uploadText():
    name = request.form.get("name", "")
    classification = request.form.get('classification', "")
    content = request.form.get('content', "")
    print(name)
    print(classification)
    print(content)
    article = Article(title=name, classfication=classification, abstract="", content=content)
    db.session.add(article)
    db.session.commit
    return "upload success"

app/main/__init__.py
from flask import Blueprint

main = Blueprint('main', __name__)

from . import views, errors

app/main/views.py
# -*- coding:utf-8 -*-
# author: zchong

from flask import render_template, redirect, request, url_for, flash, jsonify, make_response
from flask_login import login_user, login_required, logout_user
import json
from functools import partial
from app.models import Article, BlogClassify
from manage import app
import os

from . import main

@main.route('/')
@main.route('/index.html')
def index():
    return render_template('index.html')
    #return classify('9D4ABD5A8B12')
    # o = User.query.all()
    # print(o.__dict__)
    # author='zchong'
    # json_str = jsonify(o)
    # return render_template("index.html",author=author)
    # return make_response(jsonify(o.__dict__))
    # print(o.alias)
    # json_dumps = partial(json.dumps, ensure_ascii=False, sort_keys=True)
    # return jsonify("张冲是我")
    # classifys = Classify.getClassifys()

import time
import json
@main.route('/upload',methods=['GET', 'POST'])
def upload():
    path = app.config['UPLOAD_FOLDER']
    file = request.files['upfile']
    originalName = file.filename
    size = file.__sizeof__()
    type = os.path.splitext(originalName)[1]
    fileName = "%d%s" % (time.time(), type)
    file.save(os.path.join(path,fileName))
    print(file.name)
    res = {"name":fileName,
           "originalName":originalName,
           "size":size,
           "state": "SUCCESS",
           "url": fileName
           }

    return json.dumps(res)


@main.route('/blog/<int:id>/')
def showBlog(id):
    print(id + 1)
    article = Article.query.filter_by(id=id).first()

    return render_template("blog.html", article=article)


@main.route('/about.html')
def about():
    return render_template("about.html")

@main.route('/messageBoard.html')
def messageBoard():
    return render_template("messageBoard.html")

@main.route('/classify/<string:id>/')
def classify(id):

    blogs = Article.query.with_entities(Article.id, Article.title, Article.summary).join(BlogClassify).filter(
        BlogClassify.classify_id == id)
    print(blogs)
    return render_template('index.html', blogs=blogs)

@main.route('/content/<string:id>/')
def content(id):
    print(id)
    blog = Article.query.filter(id == id).first()
    return render_template('content.html',blog=blog)


@main.route('/test')
def test():
    return render_template("test.html")



@main.route('/test1',methods=['GET', 'POST'])
def test1():
    if request.method == 'POST':
        file = request.files['file']

    return '''
    <!doctype html>
    <title>Upload new File</title>
    <h1>Upload new File</h1>
    <form action="" method=post enctype=multipart/form-data>
      <p><input type=file name=file>
         <input type=submit value=Upload>
    </form>
    '''

app/templates/123.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
    <form action="{{ url_for('main.upload') }}" method="POST" enctype="multipart/form-data">
          <input type="file" name="upfile">
          <input type="submit" value="Upload">
    </form>
</body>
</html>

app/templates/about.html
<!doctype html>
<html>
<head>
<meta charset="gb2312">
<title>个人博客模板古典系列之——江南墨卷</title>
<meta name="keywords" content="个人博客模板古典系列之——江南墨卷" />
<meta name="description" content="个人博客模板古典系列之——江南墨卷" />
<link href="static/css/base.css" rel="stylesheet">
<link href="static/css/main.css" rel="stylesheet">
<!--[if lt IE 9]>
<script src="js/modernizr.js"></script>
<![endif]-->
<script type="text/javascript" src="static/js/jquery.js"></script>
</head>
<body>
<div id="wrapper">
  <header>
    <div class="headtop"></div>
    <div class="contenttop">
      <div class="logo f_l">个人博客模板古典系列之——江南墨卷</div>
      <div class="search f_r">
        <form action="/e/search/index.php" method="post" name="searchform" id="searchform">
          <input name="keyboard" id="keyboard" class="input_text" value="请输入关键字" style="color: rgb(153, 153, 153);" onfocus="if(value=='请输入关键字'){this.style.color='#000';value=''}" onblur="if(value==''){this.style.color='#999';value='请输入关键字'}" type="text">
          <input name="show" value="title" type="hidden">
          <input name="tempid" value="1" type="hidden">
          <input name="tbname" value="news" type="hidden">
          <input name="Submit" class="input_submit" value="搜索" type="submit">
        </form>
      </div>
      <div class="blank"></div>
      <nav>
        <div  class="navigation">
          <ul class="menu">
            <li><a href="index.html">网站首页</a></li>
            <li><a href="#">关于我</a>
              <ul>
                <li><a href="about.html">个人简介</a></li>
                <li><a href="listpic.html">个人相册</a></li>
              </ul>
            </li>
            <li><a href="#">我的日记</a>
              <ul>
                <li><a href="listbolg.html">个人日记</a></li>
                <li><a href="listbolg.html">学习笔记</a></li>
              </ul>
            </li>
            <li><a href="listbolg.html">技术文章</a> </li>
            <li><a href="#">给我留言</a> </li>
          </ul>
        </div>
      </nav>
      <SCRIPT type=text/javascript>
	// Navigation Menu
	$(function() {
		$(".menu ul").css({display: "none"}); // Opera Fix
		$(".menu li").hover(function(){
			$(this).find('ul:first').css({visibility: "visible",display: "none"}).slideDown("normal");
		},function(){
			$(this).find('ul:first').css({visibility: "hidden"});
		});
	});
</SCRIPT>
    </div>
  </header>
  <div class="container">
    <div class="con_content">
      <div class="about_box">
        <h2 class="nh1"><span>您现在的位置是：<a href="/" target="_blank">网站首页</a>>><a href="#" target="_blank">信息浏览</a></span><b>个人简介</b></h2>
        <div class="f_box">
          <p class="a_title">个人简介</p>
          <p class="p_title"></p>
          <!--  <p class="box_p"><span>发布时间：2017-07-07 15:12:42</span><span>作者：唐孝文</span><span>来源：稽查支队</span><span>点击：111056</span></p>-->
          <!-- 可用于内容模板 -->
        </div>
        <ul class="about_content">
          <p> 人生就是一个得与失的过程，而我却是一个幸运者，得到的永远比失去的多。生活的压力迫使我放弃了轻松的前台接待，放弃了体面的编辑，换来虽有些蓬头垢面的工作，但是我仍然很享受那些熬得只剩下黑眼圈的日子，因为我在学习使用Photoshop、Flash、Dreamweaver、ASP、PHP、JSP...中激发了兴趣，然后越走越远....</p>
          <p><img src="static/images/01.jpg"></p>
          <p>“冥冥中该来则来，无处可逃”。 </p>
        </ul>
        <!--    <div class="nextinfos">
      <p>上一篇：<a href="/">区中医医院开展志愿服务活动</a></p>
      <p>下一篇：<a href="/">广安区批准“单独两孩”500例</a></p>
    </div>-->
        <!-- 可用于内容模板 -->

        <!-- container代码 结束 -->
      </div>
    </div>
    <div class="blank"></div>
  </div>
  <!-- container代码 结束 -->

  <footer>
    <div class="footer">
      <div class="f_l">
        <p>All Rights Reserved 版权所有：<a href="http://www.yangqq.com">杨青个人博客</a> 备案号：蜀ICP备00000000号</p>
      </div>
      <div class="f_r textr">
        <p>Design by DanceSmile</p>
      </div>
    </div>
  </footer>
</div>
</body>
</html>

app/templates/base.html
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link rel="stylesheet" href="../static/css/common.css"/>
    <link rel="stylesheet" href="../static/css/index.css"/>
    {% for classify in classifys() %}
    <p>{{ classify.id }}111</p>
    <p>{{ classify.name }}2225555</p>
    {% endfor  %}

    <H3>这是一个index.html 文件{{ author }}
    </H3>
    <p>-------------------------</p>

    {% for blog in blogs %}
    <p>{{ blog.id }}111</p>
    <p>{{ blog.title }}222</p>
    <p>{{ blog.summary }}222</p>
    {% endfor  %}
</head>

app/templates/blog.html
<!doctype html>
<html>
<head>
<meta charset="gb2312">
<title>个人博客模板古典系列之——江南墨卷</title>
<meta name="keywords" content="个人博客模板古典系列之——江南墨卷" />
<meta name="description" content="个人博客模板古典系列之——江南墨卷" />
<link href="{{ url_for('static', filename='css/base.css') }}" rel="stylesheet">
<link href="{{ url_for('static', filename='css/main.css') }}" rel="stylesheet">
<!--[if lt IE 9]>
<script src="js/modernizr.js"></script>
<![endif]-->
<script type="text/javascript" src="{{ url_for('static', filename='js/jquery.js') }}"></script>
</head>
<body>
<div id="wrapper">
<header>
  <div class="headtop"></div>
  <div class="contenttop">
    <div class="logo f_l">个人博客模板古典系列之——江南墨卷</div>
    <div class="search f_r">
      <form action="/e/search/index.php" method="post" name="searchform" id="searchform">
        <input name="keyboard" id="keyboard" class="input_text" value="请输入关键字" style="color: rgb(153, 153, 153);" onfocus="if(value=='请输入关键字'){this.style.color='#000';value=''}" onblur="if(value==''){this.style.color='#999';value='请输入关键字'}" type="text">
        <input name="show" value="title" type="hidden">
        <input name="tempid" value="1" type="hidden">
        <input name="tbname" value="news" type="hidden">
        <input name="Submit" class="input_submit" value="搜索" type="submit">
      </form>
    </div>
    <div class="blank"></div>
    <nav>
      <div  class="navigation">
        <ul class="menu">
          <li><a href="index.html">网站首页</a></li>
          <li><a href="#">关于我</a>
            <ul>
              <li><a href="about.html">个人简介</a></li>
              <li><a href="listpic.html">个人相册</a></li>
            </ul>
          </li>
          <li><a href="#">我的日记</a>
            <ul>
              <li><a href="newslistpic.html">个人日记</a></li>
              <li><a href="newslistpic.html">学习笔记</a></li>
            </ul>
          </li>
          <li><a href="newslistpic.html">技术文章</a> </li>
          <li><a href="#">给我留言</a> </li>
        </ul>
      </div>
    </nav>
    <SCRIPT type=text/javascript>
	// Navigation Menu
	$(function() {
		$(".menu ul").css({display: "none"}); // Opera Fix
		$(".menu li").hover(function(){
			$(this).find('ul:first').css({visibility: "visible",display: "none"}).slideDown("normal");
		},function(){
			$(this).find('ul:first').css({visibility: "hidden"});
		});
	});
</SCRIPT>
  </div>
</header>
<div class="container">
  <div class="con_content">
    <div class="about_box">
      <h2 class="nh1"><span>您现在的位置是：<a href="/" target="_blank">网站首页</a>>><a href="#" target="_blank">个人日记</a></span><b>个人日记</b></h2>
      <div class="dtxw box">
        <li>
          <div class="dttext f_l">
            <ul>
              <h2><p>{{ article.title }}</p></h2>

                {{ article.content | safe}}
{#              <p><span style="color: rgb(63, 63, 63); font-family: &quot;microsoft yahei&quot;; white-space: normal;">最近，一直跟着公司技术牛人在搞大数据相关的东西，主要涉及的是环境搭建，同时也了解下整个hadoop生态系统相关的东西，真是让我大开眼界，这个在之后的博文中再来与大家分享。&nbsp;</span><br/><span style="color: rgb(63, 63, 63); font-family: &quot;microsoft yahei&quot;; white-space: normal;">今天，笔者给大家介绍一个代码生成器，这个是笔者的主管写的，写的确实不错，主要是基于公司的jquery easyUI + springMVC + myBatis这套框架写的，可以根据一个数据库表生成model、mapper.xml、dao接口以及service、controller、jsp页面等相关的东西，包含增删改查等操作，节省开发时间。然后，笔者在此代码生成器上修改了几个bug，同时兼容了一下mysql。&nbsp;</span><br/><span style="color: rgb(63, 63, 63); font-family: &quot;microsoft yahei&quot;; white-space: normal;">这个代码生成器工具使用的核心是freemarker，一个用Java语言编写的模板引擎，它基于模板来生成文本输出。FreeMarker与Web容器无关，即在Web运行时，它并不知道Servlet或HTTP。它不仅可以用作表现层的实现技术，而且还可以用于生成XML，JSP或Java 等。&nbsp;</span><br/><span style="color: rgb(63, 63, 63); font-family: &quot;microsoft yahei&quot;; white-space: normal;">下面，笔者开始进行核心代码的介绍。&nbsp;</span></p><p><img src="http://127.0.0.1:7088/static/upload/1513328411.JPG"/></p><p><span style="color: rgb(63, 63, 63); font-family: &quot;microsoft yahei&quot;; white-space: normal;">首先，我们必须指定哪张表，然后通过jdbc获取这个表的信息以及表字段相关的信息。&nbsp;</span><br/><span style="color: rgb(63, 63, 63); font-family: &quot;microsoft yahei&quot;; white-space: normal;">这里，将所有的配置写入config.properties：</span></p><p><span style="color: rgb(63, 63, 63); font-family: &quot;microsoft yahei&quot;; white-space: normal;"><br/></span></p><p><span style="color: rgb(63, 63, 63); font-family: &quot;microsoft yahei&quot;; white-space: normal;"><br/></span></p><p><span style="color: rgb(63, 63, 63); font-family: &quot;microsoft yahei&quot;; white-space: normal;"><br/></span></p><p><span style="color: rgb(63, 63, 63); font-family: &quot;microsoft yahei&quot;; white-space: normal;"><br/></span></p>#}

            </ul>
          </div>

{#          <div class="xwpic f_r"><a href="/"><img src="{{ url_for('static', filename='images/02.jpg') }}"></a></div>#}
        </li>
<span>{{ article.createdt }}</span>
      </div>

    </div>
  </div>
  <div class="blank"></div>
  <!-- container代码 结束 -->

  <footer>
    <div class="footer">
      <div class="f_l">
        <p>All Rights Reserved 版权所有：<a href="http://www.yangqq.com">杨青个人博客</a> 备案号：蜀ICP备00000000号</p>
      </div>
      <div class="f_r textr">
        <p>Design by DanceSmile</p>
      </div>
    </div>
  </footer>
</div>
</body>
</html>

app/templates/content.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<p>{{ blog.id }}</p>
<p>{{ blog.title }}</p>
<p>{{ blog.summary }}</p>
<p>{{ blog.content }}</p>
<p>{{ blog.create_time }}</p>
</body>
</html>

app/templates/edit.html
<!DOCTYPE HTML>
<html>
<head>

    <meta http-equiv="Content-Type" content="text/html;charset=utf-8"/>
    <title>UMEDITOR 完整demo</title>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <link href="{{ url_for('static', filename='ueditor/themes/default/css/umeditor.css') }}" type="text/css" rel="stylesheet">
    <script type="text/javascript" src="{{ url_for('static',filename='ueditor/third-party/jquery.min.js')}}"></script>
    <script type="text/javascript" src="{{ url_for('static',filename='ueditor/third-party/template.min.js')}}"></script>
    <script type="text/javascript" charset="utf-8" src="{{ url_for('static',filename='ueditor/umeditor.config.js')}}"></script>
    <script type="text/javascript" charset="utf-8" src="{{ url_for('static',filename='ueditor/umeditor.min.js')}}"></script>
    <script type="text/javascript" src="{{ url_for('static',filename='ueditor/lang/zh-cn/zh-cn.js')}}"></script>
    <style type="text/css">
        h1{
            font-family: "微软雅黑";
            font-weight: normal;
        }
        .btn {
            display: inline-block;
            *display: inline;
            padding: 4px 12px;
            margin-bottom: 0;
            *margin-left: .3em;
            font-size: 14px;
            line-height: 20px;
            color: #333333;
            text-align: center;
            text-shadow: 0 1px 1px rgba(255, 255, 255, 0.75);
            vertical-align: middle;
            cursor: pointer;
            background-color: #f5f5f5;
            *background-color: #e6e6e6;
            background-image: -moz-linear-gradient(top, #ffffff, #e6e6e6);
            background-image: -webkit-gradient(linear, 0 0, 0 100%, from(#ffffff), to(#e6e6e6));
            background-image: -webkit-linear-gradient(top, #ffffff, #e6e6e6);
            background-image: -o-linear-gradient(top, #ffffff, #e6e6e6);
            background-image: linear-gradient(to bottom, #ffffff, #e6e6e6);
            background-repeat: repeat-x;
            border: 1px solid #cccccc;
            *border: 0;
            border-color: #e6e6e6 #e6e6e6 #bfbfbf;
            border-color: rgba(0, 0, 0, 0.1) rgba(0, 0, 0, 0.1) rgba(0, 0, 0, 0.25);
            border-bottom-color: #b3b3b3;
            -webkit-border-radius: 4px;
            -moz-border-radius: 4px;
            border-radius: 4px;
            filter: progid:DXImageTransform.Microsoft.gradient(startColorstr='#ffffffff', endColorstr='#ffe6e6e6', GradientType=0);
            filter: progid:DXImageTransform.Microsoft.gradient(enabled=false);
            *zoom: 1;
            -webkit-box-shadow: inset 0 1px 0 rgba(255, 255, 255, 0.2), 0 1px 2px rgba(0, 0, 0, 0.05);
            -moz-box-shadow: inset 0 1px 0 rgba(255, 255, 255, 0.2), 0 1px 2px rgba(0, 0, 0, 0.05);
            box-shadow: inset 0 1px 0 rgba(255, 255, 255, 0.2), 0 1px 2px rgba(0, 0, 0, 0.05);
        }

        .btn:hover,
        .btn:focus,
        .btn:active,
        .btn.active,
        .btn.disabled,
        .btn[disabled] {
            color: #333333;
            background-color: #e6e6e6;
            *background-color: #d9d9d9;
        }

        .btn:active,
        .btn.active {
            background-color: #cccccc \9;
        }

        .btn:first-child {
            *margin-left: 0;
        }

        .btn:hover,
        .btn:focus {
            color: #333333;
            text-decoration: none;
            background-position: 0 -15px;
            -webkit-transition: background-position 0.1s linear;
            -moz-transition: background-position 0.1s linear;
            -o-transition: background-position 0.1s linear;
            transition: background-position 0.1s linear;
        }

        .btn:focus {
            outline: thin dotted #333;
            outline: 5px auto -webkit-focus-ring-color;
            outline-offset: -2px;
        }

        .btn.active,
        .btn:active {
            background-image: none;
            outline: 0;
            -webkit-box-shadow: inset 0 2px 4px rgba(0, 0, 0, 0.15), 0 1px 2px rgba(0, 0, 0, 0.05);
            -moz-box-shadow: inset 0 2px 4px rgba(0, 0, 0, 0.15), 0 1px 2px rgba(0, 0, 0, 0.05);
            box-shadow: inset 0 2px 4px rgba(0, 0, 0, 0.15), 0 1px 2px rgba(0, 0, 0, 0.05);
        }

        .btn.disabled,
        .btn[disabled] {
            cursor: default;
            background-image: none;
            opacity: 0.65;
            filter: alpha(opacity=65);
            -webkit-box-shadow: none;
            -moz-box-shadow: none;
            box-shadow: none;
        }
    </style>
</head>
<body>
<h1>UMEDITOR 完整demo</h1>




<div>
    <h3>标题</h3>
    <input name="title" value="测试标题" width="100px">
    <h3>类别</h3>
    <input name="classification" value="测试类别" width="100px">
</div>

<!--style给定宽度可以影响编辑器的最终宽度
 -->
<script type="text/plain" id="myEditor" style="width:1000px;height:240px;">
    <p>这里我可以写一些输入提示</p>
</script>

<div class="clear"></div>
<div id="btns">
    <button class="btn" onclick="getContent()">获得内容</button>&nbsp;
</div>


<div>
    <h3 id="focush2"></h3>
</div>
<script type="text/javascript">
    //实例化编辑器
    var um = UM.getEditor('myEditor');
    console.log(window.UMEDITOR_CONFIG);

    //按钮的操作
    function getContent() {
        var arr = [];
        arr.push(UM.getEditor('myEditor').getContent());
        var name = $("input[name='title']").val();
        var classification = $("input[name='classification']").val();
        arr.push(name);
        arr.push(classification);
        console.log(arr.join("\n"));

        $.post("{{ url_for('admin.uploadText') }}",
            {
                name: name,
                classification: classification,
                content: UM.getEditor('myEditor').getContent()
            },
            function (data) {
                alert(data)
            });
    }
</script>

</body>
</html>

app/templates/head.html
<header>
    <div class="headtop"></div>
    <div class="contenttop">
        <div class="logo f_l">&nbsp;zchong的部落格</div>
        <div class="search f_r">
            <form action="/e/search/index.php" method="post" name="searchform" id="searchform">
                <input name="keyboard" id="keyboard" class="input_text" value="请输入关键字"
                       style="color: rgb(153, 153, 153);"
                       onfocus="if(value=='请输入关键字'){this.style.color='#000';value=''}"
                       onblur="if(value==''){this.style.color='#999';value='请输入关键字'}" type="text">
                <input name="show" value="title" type="hidden">
                <input name="tempid" value="1" type="hidden">
                <input name="tbname" value="news" type="hidden">
                <input name="Submit" class="input_submit" value="搜索" type="submit">
            </form>
        </div>
        <div class="blank"></div>
        <nav>
            <div class="navigation">
                <ul class="menu">
                    <li><a href="index.html">网站首页</a></li>
                    <li><a href="#">我的日记</a>
                        <ul>
                            <li><a href="listbolg.html">个人日记</a></li>
                            <li><a href="listbolg.html">学习笔记</a></li>
                        </ul>
                    </li>
                    <li><a href="listbolg.html">技术文章</a></li>
                    <li><a href="#">关于</a>
                        <ul>
                            <li><a href="about.html">个人简介</a></li>
                            <li><a href="about.html">关于本站</a></li>
                        </ul>
                    </li>
                </ul>
            </div>
        </nav>
        <SCRIPT type=text/javascript>
            // Navigation Menu
            $(function () {
                $(".menu ul").css({display: "none"}); // Opera Fix
                $(".menu li").hover(function () {
                    $(this).find('ul:first').css({visibility: "visible", display: "none"}).slideDown("normal");
                }, function () {
                    $(this).find('ul:first').css({visibility: "hidden"});
                });
            });
        </SCRIPT>
    </div>
</header>

app/templates/test.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
    <form action="{{ url_for('main.upload') }}" method="POST" enctype="multipart/form-data">
          <input type="file" name="upfile">
          <input type="submit" value="Upload">
        <input type="hidden" name="csrf_token" value="{{ csrf_token() }}"/>
    </form>
</body>
</html>